package testes;

import java.io.*;
/**
 *
 * @author  Almedson Ferreira da Silva
 */
public class ExemploAcessoArquivo extends javax.swing.JFrame {
    
    /** Creates new form ImagemDigital */
    public ExemploAcessoArquivo() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        pnEntrada = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taEntrada = new javax.swing.JTextArea();
        bAbrir = new javax.swing.JButton();
        bSalvar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bSair = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setTitle("Ler e Salvar Arquivo");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(null);

        pnEntrada.setLayout(new java.awt.BorderLayout());

        pnEntrada.setBorder(new javax.swing.border.EtchedBorder());
        jScrollPane1.setViewportView(taEntrada);

        pnEntrada.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(pnEntrada);
        pnEntrada.setBounds(10, 80, 300, 270);

        bAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/folder_blue_open.png")));
        bAbrir.setText("Abrir Arquivo");
        bAbrir.setToolTipText("Selecionar o arquivo a ser aberto");
        bAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAbrirActionPerformed(evt);
            }
        });

        jPanel1.add(bAbrir);
        bAbrir.setBounds(10, 10, 140, 40);

        bSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/filesave.png")));
        bSalvar.setText("Salvar Arquivo");
        bSalvar.setToolTipText("Salvar o texto em arquivo");
        bSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarActionPerformed(evt);
            }
        });

        jPanel1.add(bSalvar);
        bSalvar.setBounds(150, 10, 160, 40);

        jLabel3.setFont(new java.awt.Font("MS Sans Serif", 1, 14));
        jLabel3.setText("Texto contido no Arquivo");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 60, 190, 20);

        bSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png")));
        bSair.setToolTipText("Sair do Programa");
        bSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairActionPerformed(evt);
            }
        });

        jPanel1.add(bSair);
        bSair.setBounds(270, 350, 40, 40);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/viewmag.png")));
        jButton1.setToolTipText("Dispara um evento para percorrer caractere por caractere todo o arquivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton1);
        jButton1.setBounds(10, 350, 40, 40);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-327)/2, (screenSize.height-432)/2, 327, 432);
    }//GEN-END:initComponents

    private void bSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarActionPerformed
        // TODO add your handling code here:
            javax.swing.JFileChooser arquivo = new javax.swing.JFileChooser();
        
            arquivo.setFileSelectionMode( javax.swing.JFileChooser.FILES_ONLY );
            
            int resultadoArq = arquivo.showSaveDialog( null );
            
            if( resultadoArq == javax.swing.JFileChooser.CANCEL_OPTION)
                return;
            
            File arquivoNome = arquivo.getSelectedFile();
            
            if( arquivoNome == null || arquivoNome.getName().equals(""))
                javax.swing.JOptionPane.showMessageDialog( null, "Nome de Arquivo Inválido",
                    "Nome de Arquivo Inválido", javax.swing.JOptionPane.ERROR_MESSAGE );
            else{
                
                try{
                    RandomAccessFile file = new RandomAccessFile( arquivoNome, "rw" );

                    file.writeUTF(taEntrada.getText().trim());
                    file.close();
                    
                }catch(Exception e){
                    
                }
 
            }
    }//GEN-LAST:event_bSalvarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        calcula();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    void calcula(){
        String auxString = "", capturaLetra = "", resultado = "";
        int tamanhoString = 0;
        int tipoM = 0;
        int variacaoPixel = 0;

        for(int j = 0; j < dados.size(); j++){
           
            auxString = dados.get(j).toString();
            tamanhoString = auxString.length();

            for(int i = 0; i < tamanhoString; i++){
                capturaLetra = auxString.substring( i , i+1 );

                if(!capturaLetra.equals("") )
                    resultado += capturaLetra;

            }
            resultado +="\n";
        }
    }

    private void bSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bSairActionPerformed

    private void bAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAbrirActionPerformed
        // TODO add your handling code here:
        String line_str;

        try{
            javax.swing.JFileChooser arquivo = new javax.swing.JFileChooser();
            if(arquivo.showOpenDialog(arquivo) == javax.swing.JFileChooser.APPROVE_OPTION){
                File file = arquivo.getSelectedFile();

                String textoEntrada = "";
                
                java.io.FileInputStream isTwo = new java.io.FileInputStream(  "" +file.getPath() );
                java.io.DataInputStream dsTwo = new java.io.DataInputStream(isTwo);

                dados.removeAllElements();
                
                while((line_str = dsTwo.readLine()) != null){
                    dados.add( line_str + " " );
                    textoEntrada +=  line_str + "\n";
                }
                
                taEntrada.setText(  textoEntrada  );

                dsTwo.close( );
            }
        }catch (java.io.IOException e) {
            javax.swing.JOptionPane.showMessageDialog( null, "File error: " + e.toString() );
        }
    }//GEN-LAST:event_bAbrirActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new ExemploAcessoArquivo().show();
    }
    
    private java.util.Vector dados = new java.util.Vector();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAbrir;
    private javax.swing.JButton bSair;
    private javax.swing.JButton bSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnEntrada;
    private javax.swing.JTextArea taEntrada;
    // End of variables declaration//GEN-END:variables
}

